### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by faveoled** [prateekmedia/appimagepool#70]
Hi. I've done some initial work in snapping this app. If anyone wants to takeover the snapcraft yaml is following:
```
name: appimagepool
version: '5.0.0'
summary: appimagepool
description: appimagepool
grade: stable

confinement: strict
base: core18

parts:
  appimagepool:
    plugin: flutter
    source: https://github.com/prateekmedia/appimagepool.git
    source-tag: 5.0.0
    flutter-target: lib/main.dart

apps:
  appimagepool:
    command: bin/appimagepool
    extensions: [flutter-stable]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - network
      - home
```
